name: omnibox-local

services:
  wizard:
    build: .
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      ENV: "dev"
      OBW_VECTOR_HOST: chromadb
      OBW_VECTOR_PORT: 8000
      OBW_BACKEND_BASE_URL: "http://backend:8000"
    ports:
      - "8001:8000"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://127.0.0.1:8000/api/v1/health" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    depends_on:
      chromadb:
        condition: service_healthy

  wizard-worker:
    build: .
    restart: always
    environment:
      ENV: "dev"
      OBW_VECTOR_HOST: chromadb
      OBW_VECTOR_PORT: 8000
      OBW_BACKEND_BASE_URL: "http://backend:8000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    entrypoint: [ "python", "main.py" ]
    command: [ "--workers", "1" ]
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pgrep python" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    depends_on:
      chromadb:
        condition: service_healthy

  chromadb:
    image: chromadb/chroma:1.0.7
    restart: always
    ports:
      - "8002:8000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
