name: omnibox-local

services:
  wizard:
    build: .
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      ENV: "dev"
      OBW_VECTOR_HOST: "http://meilisearch:7700"
      OBW_VECTOR_MEILI_API_KEY: ${OBW_VECTOR_MEILI_API_KEY}
      OBW_BACKEND_BASE_URL: "http://backend:8000"
    ports:
      - "8001:8000"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://127.0.0.1:8000/api/v1/health" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    depends_on:
      meilisearch:
        condition: service_healthy

  wizard-worker:
    build: .
    restart: always
    environment:
      ENV: "dev"
      OBW_VECTOR_HOST: "http://meilisearch:7700"
      OBW_VECTOR_MEILI_API_KEY: ${OBW_VECTOR_MEILI_API_KEY}
      OBW_BACKEND_BASE_URL: "http://backend:8000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    entrypoint: [ "python", "main.py" ]
    command: [ "--workers", "1" ]
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pgrep python" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    depends_on:
      meilisearch:
        condition: service_healthy

  meilisearch:
    image: getmeili/meilisearch:v1.14
    restart: always
    environment:
      MEILI_MASTER_KEY: ${OBW_VECTOR_MEILI_API_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://127.0.0.1:7700/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "7700:7700"
