name: Registry push

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - 'main'

concurrency:
  group: registry-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      can_push: ${{ steps.check_permission.outputs.can_push }}
    steps:
      - name: Check if can push
        id: check_permission
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
              echo "can_push=false" >> $GITHUB_OUTPUT
            else
              echo "can_push=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "can_push=true" >> $GITHUB_OUTPUT
          fi

  app:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'

      - name: Docker meta (app)
        id: meta_app
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/import-ai/omnibox-wizard
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io Registry
        if: needs.check.outputs.can_push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ needs.check.outputs.can_push == 'true' }}
          tags: ${{ steps.meta_app.outputs.tags }}
          labels: ${{ steps.meta_app.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  webhook:
    runs-on: ubuntu-latest
    needs: [check, app]
    if: needs.check.outputs.can_push == 'true'
    steps:
      - name: TEST push webhook
        if: github.event_name == 'push'
        env:
          WEBHOOK_URL: ${{ secrets.DEV_WEBHOOK_URL }}
          API_KEY: ${{ secrets.DEV_WEBHOOK_API_KEY }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          REF: ${{ github.ref_name }}
        run: |
          RUN_URL_ENCODED=$(jq -nr --arg url "$RUN_URL" '$url|@uri')
          REF_LINK_TEXT="${REF}"
          REF_LINK_URL="${{ github.server_url }}/${{ github.repository }}/tree/${REF}"
          curl "${WEBHOOK_URL}/test?module=wizard&ref=${REF}&commit=${GITHUB_SHA}&tag=sha-${GITHUB_SHA::7}&run_url=${RUN_URL_ENCODED}&ref_link_text=${REF_LINK_TEXT}&ref_link_url=${REF_LINK_URL}" -H "Authorization: Bearer ${API_KEY}"

      - name: TEST pull request webhook
        if: github.event_name == 'pull_request'
        env:
          WEBHOOK_URL: ${{ secrets.DEV_WEBHOOK_URL }}
          API_KEY: ${{ secrets.DEV_WEBHOOK_API_KEY }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          REF: ${{ github.head_ref }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          RUN_URL_ENCODED=$(jq -nr --arg url "$RUN_URL" '$url|@uri')
          REF_LINK_TEXT="pr-${PR_NUMBER}"
          REF_LINK_URL="${{ github.server_url }}/${{ github.repository }}/pull/${PR_NUMBER}"
          curl "${WEBHOOK_URL}/test?module=wizard&ref=${REF}&commit=${HEAD_SHA}&tag=sha-${GITHUB_SHA::7}&run_url=${RUN_URL_ENCODED}&ref_link_text=${REF_LINK_TEXT}&ref_link_url=${REF_LINK_URL}" -H "Authorization: Bearer ${API_KEY}"
